# Lines beginning with '#' are comments and are ignored by Ansible.
# Comments are used for context. Use sparringly as it could be overkill.


# pi cluster example
[pi_cluster]
pi1.local
pi2.local
pi3.local
pi4.local

[pihole]
pi1.local ansible_become=true

# Variables are only applied under the [pi_cluster] servers
[pi_cluster:vars]
ansible_user=pi

[pihole:vars]
ansible_user=pi

[proxmox]
pve1.local

# Server that is running an AMD processor and discrete GPU
[main]
main.local

# Intel CPU with integrated graphics
[support]
support.local