[pi_cluster]
pi1.local ansible_python_interpreter=/usr/bin/python3
pi2.local ansible_python_interpreter=/usr/bin/python3
pi3.local ansible_python_interpreter=/usr/bin/python3
pi4.local ansible_python_interpreter=/usr/bin/python3

; [proxmox]
; pve1.local ansible_python_interpreter=/usr/bin/python3

; [ubuntu_server]
; ubuntu1.local ansible_python_interpreter=/usr/bin/python3